const WORD_PAIRS = [
  // 🍽️ Nourriture & boissons
  ["Café", "Thé"],
  ["Pizza", "Burger"],
  ["Riz", "Pâtes"],
  ["Sushi", "Sashimi"],
  ["Fromage", "Yaourt"],
  ["Chocolat", "Bonbon"],
  ["Bière", "Vin"],
  ["Whisky", "Vodka"],
  ["Coca", "Pepsi"],
  ["Crêpe", "Gaufre"],
  ["Croissant", "Pain au chocolat"],
  ["Tarte", "Gâteau"],
  ["Glace", "Sorbet"],
  ["Miel", "Confiture"],
  ["Soupe", "Ragoût"],
  ["Steak", "Côtelette"],
  ["Crevette", "Homard"],
  ["Champagne", "Prosecco"],
  ["Rhum", "Gin"],
  ["Jus d'orange", "Smoothie"],
  ["Baguette", "Brioche"],
  ["Ketchup", "Mayonnaise"],
  ["Poivre", "Piment"],
  ["Beurre", "Margarine"],
  ["Kebab", "Tacos"],
  ["Ramen", "Nouilles"],
  ["Omelette", "Œuf au plat"],
  ["Salade", "Crudités"],
  ["Pain", "Pain de mie"],
  ["Nutella", "Pâte à tartiner"],
  ["Chips", "Frites"],
  ["Popcorn", "Cacahuètes"],
  ["Lait", "Lait d'amande"],
  ["Sel", "Sucre"],
  ["Huile", "Vinaigre"],
  ["Pastèque", "Melon"],
  ["Barbecue", "Plancha"],
  ["Fondue", "Raclette"],
  ["Couscous", "Tajine"],
  ["Paella", "Risotto"],
  ["Curry", "Tikka masala"],
  ["Croque-monsieur", "Panini"],
  ["Milkshake", "Frappé"],
  ["Cidre", "Poiré"],
  ["Mojito", "Caïpirinha"],

  // 🍇 Fruits & légumes
  ["Pomme", "Poire"],
  ["Fraise", "Framboise"],
  ["Citron", "Citron vert"],
  ["Banane", "Plantain"],
  ["Orange", "Mandarine"],
  ["Cerise", "Prune"],
  ["Ananas", "Mangue"],
  ["Kiwi", "Litchi"],
  ["Carotte", "Navet"],
  ["Tomate", "Poivron"],
  ["Courgette", "Aubergine"],
  ["Pomme de terre", "Patate douce"],
  ["Oignon", "Échalote"],
  ["Champignon", "Truffe"],
  ["Brocoli", "Chou-fleur"],
  ["Épinard", "Salade verte"],
  ["Ail", "Gingembre"],
  ["Raisin", "Groseille"],
  ["Avocat", "Concombre"],
  ["Radis", "Betterave"],

  // 🐾 Animaux
  ["Chien", "Chat"],
  ["Tigre", "Lion"],
  ["Loup", "Renard"],
  ["Aigle", "Faucon"],
  ["Dauphin", "Baleine"],
  ["Serpent", "Lézard"],
  ["Cheval", "Âne"],
  ["Mouton", "Chèvre"],
  ["Ours", "Panda"],
  ["Perroquet", "Perruche"],
  ["Abeille", "Guêpe"],
  ["Araignée", "Scorpion"],
  ["Requin", "Barracuda"],
  ["Hibou", "Chouette"],
  ["Grenouille", "Crapaud"],
  ["Tortue", "Escargot"],
  ["Girafe", "Zèbre"],
  ["Singe", "Gorille"],
  ["Souris", "Rat"],
  ["Papillon", "Libellule"],
  ["Vache", "Bison"],
  ["Cochon", "Sanglier"],
  ["Poule", "Coq"],
  ["Canard", "Oie"],
  ["Hérisson", "Écureuil"],
  ["Kangourou", "Koala"],
  ["Éléphant", "Rhinocéros"],
  ["Crocodile", "Alligator"],
  ["Pieuvre", "Calamar"],
  ["Méduse", "Anémone"],
  ["Fourmi", "Termite"],
  ["Moustique", "Mouche"],
  ["Coccinelle", "Scarabée"],
  ["Flamant rose", "Cigogne"],
  ["Panthère", "Léopard"],
  ["Chameau", "Dromadaire"],
  ["Paon", "Faisan"],
  ["Loutre", "Castor"],
  ["Pingouin", "Manchot"],
  ["Iguane", "Caméléon"],

  // 🚗 Transports
  ["Voiture", "Moto"],
  ["Train", "Avion"],
  ["Vélo", "Trottinette"],
  ["Skateboard", "Rollers"],
  ["Bateau", "Voilier"],
  ["Bus", "Tramway"],
  ["Hélicoptère", "Avion"],
  ["Camion", "Fourgon"],
  ["Métro", "RER"],
  ["Taxi", "VTC"],
  ["Fusée", "Navette spatiale"],
  ["Scooter", "Mobylette"],
  ["Yacht", "Péniche"],
  ["Sous-marin", "Bateau de pêche"],
  ["Tracteur", "Bulldozer"],
  ["Montgolfière", "Deltaplane"],
  ["Charrette", "Carrosse"],
  ["Téléphérique", "Funiculaire"],

  // 📱 Technologie & réseaux sociaux
  ["Netflix", "YouTube"],
  ["Facebook", "Instagram"],
  ["Twitter", "TikTok"],
  ["Iphone", "Samsung"],
  ["WhatsApp", "Messenger"],
  ["Spotify", "Deezer"],
  ["PlayStation", "Xbox"],
  ["Google", "Bing"],
  ["Uber", "Bolt"],
  ["Zoom", "Teams"],
  ["Gmail", "Outlook"],
  ["Amazon", "Cdiscount"],
  ["LinkedIn", "Indeed"],
  ["Snapchat", "BeReal"],
  ["Windows", "MacOS"],
  ["Clavier", "Souris"],
  ["Tablette", "Liseuse"],
  ["Casque", "Écouteurs"],
  ["Chargeur", "Batterie externe"],
  ["Imprimante", "Scanner"],
  ["Drone", "Télécommande"],
  ["Enceinte", "Barre de son"],
  ["Wifi", "Bluetooth"],
  ["Application", "Logiciel"],
  ["Webcam", "Appareil photo"],

  // 🌦️ Nature & saisons
  ["Hiver", "Automne"],
  ["Lune", "Soleil"],
  ["Pluie", "Neige"],
  ["Montagne", "Colline"],
  ["Océan", "Piscine"],
  ["Rivière", "Lac"],
  ["Désert", "Savane"],
  ["Volcan", "Séisme"],
  ["Orage", "Tempête"],
  ["Forêt", "Jungle"],
  ["Étoile", "Planète"],
  ["Nuage", "Brouillard"],
  ["Arc-en-ciel", "Aurore boréale"],
  ["Sable", "Terre"],
  ["Glacier", "Iceberg"],
  ["Cascade", "Fontaine"],
  ["Marée", "Vague"],
  ["Éclair", "Tonnerre"],
  ["Grêle", "Verglas"],
  ["Vent", "Ouragan"],

  // 🪐 Espace
  ["Mars", "Vénus"],
  ["Astronaute", "Cosmonaute"],
  ["Comète", "Astéroïde"],
  ["Galaxie", "Constellation"],
  ["Trou noir", "Étoile filante"],
  ["Système solaire", "Voie lactée"],
  ["Satellite", "Station spatiale"],
  ["Télescope", "Jumelles"],
  ["Extraterrestre", "Alien"],
  ["Éclipse", "Équinoxe"],

  // 🏅 Sports
  ["Foot", "Rugby"],
  ["Boxe", "Karaté"],
  ["Basket", "Handball"],
  ["Tennis", "Badminton"],
  ["Natation", "Plongée"],
  ["Ski", "Snowboard"],
  ["Golf", "Bowling"],
  ["Judo", "Taekwondo"],
  ["Escalade", "Randonnée"],
  ["Cyclisme", "Triathlon"],
  ["Volleyball", "Beach-volley"],
  ["Marathon", "Sprint"],
  ["Yoga", "Pilates"],
  ["Surf", "Bodyboard"],
  ["Patinage", "Hockey"],
  ["Équitation", "Polo"],
  ["Fléchettes", "Billard"],
  ["Aviron", "Kayak"],
  ["Escrime", "Tir à l'arc"],
  ["Haltérophilie", "Musculation"],
  ["Pétanque", "Curling"],
  ["Water-polo", "Plongeon"],

  // 💃 Danse
  ["Salsa", "Bachata"],
  ["Tango", "Valse"],
  ["Hip-hop", "Break dance"],
  ["Ballet", "Danse contemporaine"],
  ["Zumba", "Aérobic"],

  // 💼 Métiers
  ["Docteur", "Infirmier"],
  ["Professeur", "Directeur"],
  ["Roi", "Président"],
  ["Avocat", "Juge"],
  ["Pompier", "Policier"],
  ["Boulanger", "Pâtissier"],
  ["Architecte", "Ingénieur"],
  ["Chanteur", "Musicien"],
  ["Acteur", "Réalisateur"],
  ["Journaliste", "Écrivain"],
  ["Coiffeur", "Esthéticienne"],
  ["Vétérinaire", "Éleveur"],
  ["Facteur", "Livreur"],
  ["Pilote", "Steward"],
  ["Cuisinier", "Serveur"],
  ["Comptable", "Banquier"],
  ["Plombier", "Électricien"],
  ["Menuisier", "Charpentier"],
  ["Agriculteur", "Jardinier"],
  ["Chirurgien", "Dentiste"],
  ["Psychologue", "Psychiatre"],
  ["Traducteur", "Interprète"],
  ["Photographe", "Vidéaste"],
  ["Notaire", "Huissier"],
  ["Mécanicien", "Garagiste"],
  ["Boucher", "Poissonnier"],
  ["Douanier", "Militaire"],
  ["Bibliothécaire", "Archiviste"],

  // 🏙️ Lieux & bâtiments
  ["Château", "Palais"],
  ["Bibliothèque", "Librairie"],
  ["Camping", "Hôtel"],
  ["Banque", "Poste"],
  ["Cinéma", "Théâtre"],
  ["Hôpital", "Clinique"],
  ["Piscine", "Spa"],
  ["École", "Université"],
  ["Église", "Mosquée"],
  ["Musée", "Galerie"],
  ["Supermarché", "Marché"],
  ["Aéroport", "Gare"],
  ["Restaurant", "Fast-food"],
  ["Mairie", "Préfecture"],
  ["Stade", "Gymnase"],
  ["Parc", "Jardin"],
  ["Prison", "Caserne"],
  ["Ferme", "Zoo"],
  ["Usine", "Entrepôt"],
  ["Tour", "Gratte-ciel"],
  ["Pont", "Tunnel"],
  ["Phare", "Port"],
  ["Cimetière", "Crématorium"],
  ["Auberge", "Refuge"],
  ["Pharmacie", "Parapharmacie"],
  ["Station-service", "Garage"],
  ["Salle de sport", "Piste d'athlétisme"],

  // 🌍 Pays & continents
  ["France", "Belgique"],
  ["Italie", "Espagne"],
  ["Chine", "Japon"],
  ["Canada", "États-Unis"],
  ["Brésil", "Argentine"],
  ["Maroc", "Algérie"],
  ["Allemagne", "Autriche"],
  ["Portugal", "Grèce"],
  ["Égypte", "Tunisie"],
  ["Inde", "Pakistan"],
  ["Russie", "Ukraine"],
  ["Suède", "Norvège"],
  ["Mexique", "Cuba"],
  ["Australie", "Nouvelle-Zélande"],
  ["Afrique", "Asie"],

  // 🏛️ Villes
  ["Paris", "Londres"],
  ["New York", "Los Angeles"],
  ["Tokyo", "Séoul"],
  ["Rome", "Venise"],
  ["Barcelone", "Madrid"],
  ["Berlin", "Munich"],
  ["Marseille", "Nice"],
  ["Dubaï", "Abu Dhabi"],
  ["Amsterdam", "Bruxelles"],
  ["Le Caire", "Casablanca"],

  // 🎬 Divertissement & fiction
  ["Comédie", "Drame"],
  ["Vampire", "Zombie"],
  ["Robot", "Extraterrestre"],
  ["Sorcier", "Magicien"],
  ["Fantôme", "Squelette"],
  ["Super-héros", "Justicier"],
  ["Pirate", "Corsaire"],
  ["Chevalier", "Gladiateur"],
  ["Guitare", "Piano"],
  ["Batterie", "Violon"],
  ["Karaoké", "Concert"],
  ["Festival", "Carnaval"],
  ["Roman", "Bande dessinée"],
  ["Podcast", "Radio"],
  ["Fée", "Elfe"],
  ["Dragon", "Licorne"],
  ["Loup-garou", "Ogre"],
  ["Momie", "Squelette"],
  ["Ninja", "Samouraï"],
  ["Cowboy", "Shérif"],
  ["Espion", "Détective"],
  ["Clown", "Magicien"],

  // 🎮 Jeux vidéo
  ["Console", "PC"],
  ["Manette", "Joystick"],
  ["Fortnite", "Minecraft"],
  ["FIFA", "PES"],
  ["Mario", "Sonic"],
  ["Pokémon", "Digimon"],
  ["GTA", "Watch Dogs"],
  ["Casque VR", "Lunettes 3D"],
  ["Arcade", "Flipper"],
  ["Jeu de société", "Jeu de cartes"],

  // 🎵 Musique - genres & instruments
  ["Rock", "Metal"],
  ["Rap", "Slam"],
  ["Jazz", "Blues"],
  ["Techno", "House"],
  ["Reggae", "Ska"],
  ["Pop", "Variété"],
  ["Classique", "Opéra"],
  ["Flûte", "Clarinette"],
  ["Trompette", "Saxophone"],
  ["Harpe", "Violoncelle"],

  // 🧑‍🎓 École & matières
  ["Mathématiques", "Physique"],
  ["Histoire", "Géographie"],
  ["Français", "Anglais"],
  ["Biologie", "Chimie"],
  ["Sport", "EPS"],
  ["Recréation", "Pause déjeuner"],
  ["Examen", "Contrôle"],
  ["Cahier", "Classeur"],
  ["Trousse", "Cartable"],
  ["Tableau", "Vidéoprojecteur"],

  // 🎉 Fêtes & évènements
  ["Noël", "Nouvel An"],
  ["Halloween", "Carnaval"],
  ["Anniversaire", "Mariage"],
  ["Pâques", "Saint-Valentin"],
  ["Barbecue", "Pique-nique"],
  ["Feu d'artifice", "Pétard"],
  ["Kermesse", "Foire"],
  ["Réveillon", "Soirée"],

  // 🔬 Sciences & inventeurs
  ["Einstein", "Newton"],
  ["Darwin", "Pasteur"],
  ["Marie Curie", "Ada Lovelace"],
  ["Galilée", "Copernic"],
  ["Tesla", "Edison"],

  // 🎨 Peintres & artistes
  ["Picasso", "Van Gogh"],
  ["Monet", "Renoir"],
  ["Dali", "Magritte"],
  ["Michel-Ange", "Léonard de Vinci"],

  // 📜 Mythologie & contes
  ["Zeus", "Poséidon"],
  ["Hercule", "Achille"],
  ["Cendrillon", "Blanche-Neige"],
  ["Petit Chaperon rouge", "Boucle d'or"],
  ["Sirène", "Nymphe"],
  ["Phénix", "Griffon"],

  // 😀 Émotions
  ["Joie", "Bonheur"],
  ["Tristesse", "Mélancolie"],
  ["Colère", "Rage"],
  ["Peur", "Angoisse"],
  ["Surprise", "Étonnement"],
  ["Jalousie", "Envie"],
  ["Fierté", "Confiance"],
  ["Honte", "Gêne"],
  ["Ennui", "Lassitude"],
  ["Stress", "Anxiété"],

  // 🧍 Corps humain
  ["Main", "Pied"],
  ["Bras", "Jambe"],
  ["Œil", "Oreille"],
  ["Nez", "Bouche"],
  ["Cœur", "Poumon"],
  ["Cerveau", "Colonne vertébrale"],
  ["Cheveux", "Barbe"],
  ["Dent", "Ongle"],
  ["Genou", "Coude"],
  ["Épaule", "Hanche"],

  // 👨‍👩‍👧 Famille & relations
  ["Père", "Mère"],
  ["Frère", "Sœur"],
  ["Grand-père", "Grand-mère"],
  ["Oncle", "Tante"],
  ["Cousin", "Neveu"],
  ["Mari", "Femme"],
  ["Ami", "Voisin"],
  ["Bébé", "Enfant"],

  // 👕 Vêtements & accessoires
  ["Montre", "Bracelet"],
  ["Lunettes", "Lentilles"],
  ["Parapluie", "Imperméable"],
  ["Valise", "Sac à dos"],
  ["Portefeuille", "Sac à main"],
  ["Chapeau", "Casquette"],
  ["Écharpe", "Gants"],
  ["Chaussures", "Baskets"],
  ["Robe", "Jupe"],
  ["Costume", "Smoking"],
  ["Pull", "Gilet"],
  ["Ceinture", "Bretelles"],
  ["Bijou", "Collier"],
  ["Cravate", "Nœud papillon"],

  // 🛋️ Maison & meubles
  ["Chaise", "Tabouret"],
  ["Canapé", "Fauteuil"],
  ["Bougie", "Lampe"],
  ["Miroir", "Photo"],
  ["Table", "Bureau"],
  ["Lit", "Matelas"],
  ["Armoire", "Commode"],
  ["Rideau", "Store"],
  ["Tapis", "Moquette"],
  ["Étagère", "Bibliothèque"],
  ["Frigo", "Congélateur"],
  ["Four", "Micro-ondes"],
  ["Aspirateur", "Balai"],
  ["Douche", "Baignoire"],

  // 🔧 Outils & bricolage
  ["Marteau", "Tournevis"],
  ["Perceuse", "Visseuse"],
  ["Clou", "Vis"],
  ["Pince", "Tenaille"],
  ["Scie", "Hache"],
  ["Peinture", "Vernis"],
  ["Échelle", "Escabeau"],
  ["Colle", "Scotch"],

  // ✍️ Objets du quotidien
  ["Stylo", "Crayon"],
  ["Cahier", "Bloc-notes"],
  ["Ciseaux", "Cutter"],
  ["Horloge", "Réveil"],
  ["Clé", "Cadenas"],
  ["Poubelle", "Recyclage"],
  ["Boîte", "Carton"],
  ["Panier", "Sac"],

  // 🎨 Couleurs
  ["Rouge", "Orange"],
  ["Bleu", "Turquoise"],
  ["Vert", "Kaki"],
  ["Jaune", "Doré"],
  ["Noir", "Gris"],
  ["Blanc", "Beige"],
  ["Violet", "Mauve"],
  ["Rose", "Fuchsia"],

  // ⚙️ Matériaux
  ["Or", "Argent"],
  ["Fer", "Acier"],
  ["Bois", "Bambou"],
  ["Verre", "Cristal"],
  ["Plastique", "Silicone"],
  ["Cuir", "Daim"],
  ["Laine", "Coton"],
  ["Diamant", "Rubis"],

  // 🍽️ Nourriture supplémentaire
  ["Sandwich", "Wrap"],
  ["Nachos", "Tortillas"],
  ["Ravioli", "Tortellini"],
  ["Falafel", "Houmous"],
  ["Bagel", "Muffin"],
  ["Churros", "Beignets"],
  ["Macaron", "Meringue"],
  ["Flan", "Crème brûlée"],
  ["Tiramisu", "Panna cotta"],
  ["Pho", "Bo bun"],
  ["Yakitori", "Brochette"],
  ["Guacamole", "Salsa"],
  ["Burrito", "Quesadilla"],
  ["Hot-dog", "Sandwich chaud"],
  ["Escargot", "Cuisse de grenouille"],
  ["Foie gras", "Pâté"],
  ["Cassoulet", "Pot-au-feu"],
  ["Bouillabaisse", "Soupe de poisson"],
  ["Bibimbap", "Riz sauté"],
  ["Dim sum", "Nem"],
  ["Pretzel", "Biscuit salé"],
  ["Granité", "Sorbet"],
  ["Thé glacé", "Limonade"],
  ["Cappuccino", "Café latte"],
  ["Espresso", "Ristretto"],
  ["Chocolat chaud", "Café au lait"],
  ["Confit de canard", "Magret"],
  ["Andouillette", "Boudin"],
  ["Merguez", "Chipolata"],
  ["Quiche", "Tarte salée"],
  ["Gratin", "Purée"],
  ["Velouté", "Potage"],

  // 🍇 Fruits & légumes supplémentaire
  ["Grenade", "Figue"],
  ["Datte", "Abricot sec"],
  ["Nectarine", "Pêche"],
  ["Clémentine", "Satsuma"],
  ["Physalis", "Groseille à maquereau"],
  ["Poireau", "Céleri"],
  ["Panais", "Rutabaga"],
  ["Chou", "Chou de Bruxelles"],
  ["Haricot vert", "Petit pois"],
  ["Maïs", "Blé"],
  ["Lentille", "Pois chiche"],
  ["Cacahuète", "Noix de cajou"],
  ["Noix", "Noisette"],
  ["Amande", "Pistache"],
  ["Fenouil", "Artichaut"],

  // 🐾 Animaux supplémentaire
  ["Furet", "Belette"],
  ["Lynx", "Puma"],
  ["Hyène", "Chacal"],
  ["Bouquetin", "Chamois"],
  ["Marmotte", "Blaireau"],
  ["Vautour", "Charognard"],
  ["Corbeau", "Corneille"],
  ["Pélican", "Cormoran"],
  ["Toucan", "Perroquet ara"],
  ["Colibri", "Moineau"],
  ["Anguille", "Murène"],
  ["Raie", "Requin-marteau"],
  ["Hippocampe", "Poisson-clown"],
  ["Étoile de mer", "Oursin"],
  ["Crabe", "Bernard-l'ermite"],
  ["Ver de terre", "Sangsue"],
  ["Mille-pattes", "Cloporte"],
  ["Puce", "Tique"],
  ["Cigale", "Criquet"],
  ["Sauterelle", "Grillon"],
  ["Otarie", "Phoque"],
  ["Morse", "Narval"],
  ["Ornithorynque", "Échidné"],
  ["Wombat", "Opossum"],
  ["Paresseux", "Tatou"],
  ["Merle", "Rossignol"],
  ["Pigeon", "Tourterelle"],
  ["Autruche", "Émeu"],

  // 🚗 Transports supplémentaire
  ["Caravane", "Camping-car"],
  ["Quad", "Buggy"],
  ["Traîneau", "Luge"],
  ["Téléski", "Télésiège"],
  ["Pirogue", "Canoë"],
  ["Jet-ski", "Scooter des mers"],
  ["Porte-avions", "Cuirassé"],
  ["Zeppelin", "Dirigeable"],
  ["Chariot élévateur", "Grue"],
  ["Corbillard", "Fourgon funéraire"],

  // 📱 Technologie supplémentaire
  ["Discord", "Slack"],
  ["Reddit", "Forum"],
  ["Twitch", "YouTube Gaming"],
  ["Pinterest", "Instagram"],
  ["Airbnb", "Booking"],
  ["PayPal", "Venmo"],
  ["Netflix", "Disney+"],
  ["Alexa", "Siri"],
  ["Robot aspirateur", "Aspirateur balai"],
  ["Disque dur", "Clé USB"],
  ["Carte graphique", "Processeur"],
  ["Écran", "Moniteur"],
  ["Routeur", "Modem"],
  ["VPN", "Proxy"],

  // 🌦️ Nature supplémentaire
  ["Roche", "Caillou"],
  ["Falaise", "Ravin"],
  ["Plaine", "Plateau"],
  ["Marais", "Marécage"],
  ["Récif", "Corail"],
  ["Geyser", "Source chaude"],
  ["Stalactite", "Stalagmite"],
  ["Mousson", "Sécheresse"],
  ["Permafrost", "Toundra"],
  ["Écosystème", "Biotope"],

  // 🏅 Sports supplémentaire
  ["Rugby à XV", "Rugby à VII"],
  ["Cricket", "Baseball"],
  ["Squash", "Padel"],
  ["Biathlon", "Ski de fond"],
  ["Bobsleigh", "Luge de course"],
  ["Trampoline", "Gymnastique"],
  ["Fitness", "Crossfit"],
  ["Motocross", "Rallye"],
  ["Voile", "Planche à voile"],
  ["Skateboard", "BMX"],
  ["Free-fight", "Boxe thaï"],
  ["Tir sportif", "Chasse"],

  // 💼 Métiers supplémentaire
  ["Steward", "Hôtesse de l'air"],
  ["Sage-femme", "Gynécologue"],
  ["Ostéopathe", "Kinésithérapeute"],
  ["Serrurier", "Vitrier"],
  ["Peintre en bâtiment", "Décorateur"],
  ["Chauffeur", "Livreur"],
  ["Éboueur", "Agent d'entretien"],
  ["Astronome", "Physicien"],
  ["Biologiste", "Botaniste"],
  ["Géologue", "Archéologue"],
  ["Diplomate", "Ambassadeur"],
  ["Analyste financier", "Trader"],
  ["Community manager", "Influenceur"],
  ["Designer", "Graphiste"],
  ["Développeur", "Programmeur"],

  // 🏙️ Lieux supplémentaire
  ["Skatepark", "Terrain de basket"],
  ["Patinoire", "Bowling"],
  ["Karting", "Circuit automobile"],
  ["Aquarium", "Parc animalier"],
  ["Planétarium", "Observatoire"],
  ["Amphithéâtre", "Arène"],
  ["Monastère", "Abbaye"],
  ["Chapelle", "Cathédrale"],
  ["Forteresse", "Citadelle"],
  ["Moulin", "Fabrique"],
  ["Marina", "Quai"],
  ["Barrage", "Centrale électrique"],

  // 🌍 Pays supplémentaire
  ["Suisse", "Liechtenstein"],
  ["Pays-Bas", "Luxembourg"],
  ["Turquie", "Grèce"],
  ["Iran", "Irak"],
  ["Vietnam", "Laos"],
  ["Thaïlande", "Cambodge"],
  ["Chili", "Pérou"],
  ["Colombie", "Venezuela"],
  ["Kenya", "Éthiopie"],
  ["Sénégal", "Côte d'Ivoire"],

  // 🏛️ Villes supplémentaire
  ["Lyon", "Toulouse"],
  ["Bordeaux", "Nantes"],
  ["Lisbonne", "Porto"],
  ["Vienne", "Budapest"],
  ["Prague", "Varsovie"],
  ["Moscou", "Saint-Pétersbourg"],
  ["Pékin", "Shanghai"],
  ["Bangkok", "Hanoï"],
  ["Rio de Janeiro", "São Paulo"],
  ["Montréal", "Toronto"],

  // 🎬 Divertissement supplémentaire
  ["Mangas", "Comics"],
  ["Anime", "Dessin animé"],
  ["Court-métrage", "Long-métrage"],
  ["Documentaire", "Reportage"],
  ["Sitcom", "Série dramatique"],
  ["Thriller", "Policier"],
  ["Science-fiction", "Fantastique"],
  ["Horreur", "Épouvante"],
  ["Western", "Aventure"],
  ["Musical", "Comédie musicale"],
  ["Stand-up", "One-man-show"],
  ["Cascadeur", "Doublure"],

  // 🎮 Jeux vidéo supplémentaire
  ["League of Legends", "Dota"],
  ["Call of Duty", "Battlefield"],
  ["The Sims", "Animal Crossing"],
  ["Roblox", "Minecraft"],
  ["Among Us", "Loup-garou"],
  ["Candy Crush", "Bejeweled"],
  ["Tetris", "Puzzle"],
  ["Zelda", "Final Fantasy"],

  // 🎵 Musique supplémentaire
  ["R&B", "Soul"],
  ["Country", "Folk"],
  ["Disco", "Funk"],
  ["K-pop", "J-pop"],
  ["Chorale", "Orchestre"],
  ["Concert live", "Album studio"],
  ["Microphone", "Enceinte de scène"],
  ["Métronome", "Accordeur"],

  // 🧑‍🎓 École supplémentaire
  ["Rentrée scolaire", "Vacances"],
  ["Diplôme", "Certificat"],
  ["Bourse d'études", "Prêt étudiant"],
  ["Colle", "Retenue"],
  ["Internat", "Externat"],

  // 🎉 Fêtes supplémentaire
  ["Confettis", "Serpentins"],
  ["Ballon", "Guirlande"],
  ["Cadeau", "Carte de vœux"],
  ["Bougie d'anniversaire", "Gâteau d'anniversaire"],
  ["Cotillons", "Pétards"],

  // 😀 Émotions supplémentaire
  ["Nostalgie", "Regret"],
  ["Espoir", "Optimisme"],
  ["Solitude", "Isolement"],
  ["Curiosité", "Émerveillement"],
  ["Culpabilité", "Remords"],

  // 🧍 Corps supplémentaire
  ["Poignet", "Cheville"],
  ["Sourcil", "Cil"],
  ["Peau", "Muscle"],
  ["Foie", "Rein"],
  ["Estomac", "Intestin"],

  // 👕 Vêtements supplémentaire
  ["Maillot de bain", "Combinaison de plongée"],
  ["Pyjama", "Chemise de nuit"],
  ["Peignoir", "Robe de chambre"],
  ["Salopette", "Combinaison"],
  ["Bermuda", "Short"],
  ["Doudoune", "Anorak"],
  ["Chaussettes", "Collants"],
  ["Débardeur", "T-shirt"],

  // 🛋️ Maison supplémentaire
  ["Cheminée", "Poêle à bois"],
  ["Balcon", "Terrasse"],
  ["Grenier", "Cave"],
  ["Garage", "Abri de jardin"],
  ["Volet", "Fenêtre"],
  ["Sonnette", "Interphone"],
  ["Coussin", "Plaid"],
  ["Vaisselle", "Couverts"],

  // ✍️ Objets supplémentaire
  ["Agrafeuse", "Perforatrice"],
  ["Trombone", "Épingle"],
  ["Enveloppe", "Timbre"],
  ["Calculatrice", "Boulier"],
  ["Loupe", "Jumelles"],
  ["Torche", "Lampe de poche"],

  // 🎨 Couleurs supplémentaire
  ["Marron", "Chocolat"],
  ["Indigo", "Bleu marine"],
  ["Corail", "Saumon"],
  ["Bordeaux", "Grenat"],

  // ⚙️ Matériaux supplémentaire
  ["Béton", "Ciment"],
  ["Marbre", "Granit"],
  ["Céramique", "Porcelaine"],
  ["Titane", "Aluminium"],

  // 💰 Argent & finance
  ["Bourse", "Marché financier"],
  ["Crédit", "Débit"],
  ["Action", "Obligation"],
  ["Bitcoin", "Ethereum"],
  ["Espèces", "Carte bancaire"],
  ["Économie", "Épargne"],

  // 🕰️ Temps
  ["Matin", "Après-midi"],
  ["Semaine", "Mois"],
  ["Aube", "Crépuscule"],
  ["Minute", "Seconde"],
  ["Passé", "Futur"],

  // 🏥 Santé
  ["Fièvre", "Rhume"],
  ["Vaccin", "Médicament"],
  ["Pansement", "Bandage"],
  ["Béquille", "Fauteuil roulant"],
  ["Thermomètre", "Tensiomètre"],
  ["Sirop", "Comprimé"],

  // 🌐 Internet & jargon
  ["Émoji", "Sticker"],
  ["Hashtag", "Mention"],
  ["Story", "Post"],
  ["Influenceur", "Youtubeur"],
  ["Meme", "GIF"],

  // 🏞️ Activités de loisir
  ["Pêche", "Chasse"],
  ["Randonnée", "Trekking"],
  ["Puzzle", "Sudoku"],
  ["Origami", "Scrapbooking"],
  ["Poterie", "Sculpture"],
  ["Peinture", "Dessin"],
  ["Photographie", "Vidéographie"],
  ["Jardinage", "Bricolage"],

  // 🧩 Jeux traditionnels
  ["Échecs", "Dames"],
  ["Dominos", "Cartes"],
  ["Mikado", "Jenga"],
  ["Loto", "Bingo"],
  ["Cache-cache", "Colin-maillard"],
  ["Corde à sauter", "Élastique"],
  ["Marelle", "Billes"],

  // 🚀 Sciences & tech supplémentaire
  ["Intelligence artificielle", "Robotique"],
  ["Nanotechnologie", "Biotechnologie"],
  ["Énergie solaire", "Énergie éolienne"],
  ["Réacteur nucléaire", "Centrale hydraulique"],
  ["ADN", "ARN"],
  ["Atome", "Molécule"],

  // 🧴 Beauté & hygiène
  ["Shampoing", "Après-shampoing"],
  ["Savon", "Gel douche"],
  ["Parfum", "Déodorant"],
  ["Rasoir", "Tondeuse"],
  ["Rouge à lèvres", "Gloss"],
  ["Vernis à ongles", "Dissolvant"],

  // 🍹 Boissons supplémentaire
  ["Eau gazeuse", "Eau plate"],
  ["Cocktail", "Mocktail"],
  ["Sirop", "Soda"],
  ["Infusion", "Tisane"],

  // 📚 Littérature
  ["Roman policier", "Roman d'amour"],
  ["Poésie", "Théâtre"],
  ["Autobiographie", "Biographie"],
  ["Conte", "Fable"],
  ["Nouvelle", "Essai"],

  // 🕹️ Divers
  ["Casino", "Loterie"],
  ["Cirque", "Spectacle de rue"],
  ["Marionnette", "Théâtre d'ombres"],
  ["Feu de camp", "Barbecue"],
  ["Igloo", "Cabane"],
  ["Tente", "Yourte"],
  ["Hamac", "Chaise longue"],

  // 🎭 Traits de personnalité
  ["Optimiste", "Pessimiste"],
  ["Introverti", "Extraverti"],
  ["Timide", "Audacieux"],
  ["Généreux", "Avare"],
  ["Patient", "Impatient"],
  ["Calme", "Nerveux"],
  ["Honnête", "Menteur"],
  ["Curieux", "Indifférent"],

  // 🌡️ Climat & météo supplémentaire
  ["Canicule", "Vague de froid"],
  ["Humidité", "Sécheresse"],
  ["Climat tropical", "Climat polaire"],
  ["Saison sèche", "Saison des pluies"],

  // 🏗️ Bâtiment & construction
  ["Chantier", "Échafaudage"],
  ["Grue", "Bétonnière"],
  ["Fondations", "Charpente"],
  ["Isolation", "Étanchéité"],

  // 🎪 Cirque & spectacle
  ["Trapéziste", "Funambule"],
  ["Dompteur", "Dresseur"],
  ["Jongleur", "Acrobate"],
  ["Contorsionniste", "Équilibriste"],

  // 🧵 Couture & artisanat
  ["Aiguille", "Fil"],
  ["Machine à coudre", "Tricot"],
  ["Bouton", "Fermeture éclair"],
  ["Tissu", "Cuir synthétique"],

  // 🏛️ Société & institutions
  ["Démocratie", "République"],
  ["Élection", "Référendum"],
  ["Loi", "Règlement"],
  ["Impôt", "Taxe"],
  ["Grève", "Manifestation"],
  ["Syndicat", "Association"],

  // 🧭 Géographie physique
  ["Continent", "Île"],
  ["Hémisphère", "Équateur"],
  ["Latitude", "Longitude"],
  ["Frontière", "Douane"],
  ["Capitale", "Métropole"],

  // 🐉 Créatures fantastiques
  ["Gobelin", "Troll"],
  ["Centaure", "Minotaure"],
  ["Golem", "Gargouille"],
  ["Djinn", "Génie"],

  // 🧠 Psychologie & concepts
  ["Mémoire", "Concentration"],
  ["Créativité", "Imagination"],
  ["Logique", "Intuition"],
  ["Conscience", "Inconscient"],

  // 🍂 Agriculture
  ["Récolte", "Semis"],
  ["Élevage", "Pâturage"],
  ["Serre", "Champ"],
  ["Irrigation", "Arrosage"],
  ["Pesticide", "Engrais"],

  // 🎖️ Vocabulaire militaire général
  ["Soldat", "Officier"],
  ["Char d'assaut", "Blindé"],
  ["Uniforme", "Treillis"],
  ["Caserne", "Base militaire"],
];
